<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
 <modelVersion>4.0.0</modelVersion>
 <parent>
  <groupId>labs.apps.backend.java.langgraph4j</groupId>
  <artifactId>langgraph4j</artifactId>
  <version>${revision}</version>
 </parent>
 <groupId>labs.apps.backend.java.langgraph4j.example</groupId>
 <artifactId>example</artifactId>
 <packaging>pom</packaging>
 
 <modules>
  <module>langgraph4j-1-simple</module>
 </modules>

</project>
