<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
 <modelVersion>4.0.0</modelVersion>
 <parent>
  <groupId>labs.apps.backend.java.spring.examples</groupId>
  <artifactId>examples</artifactId>
  <version>${revision}</version>
 </parent>
 <groupId>labs.apps.backend.java.spring.examples.langgraph4j</groupId>
 <artifactId>langgraph4j-1-simplegraphapp</artifactId>
 <packaging>war</packaging>

 <dependencies>
  <!-- Langchain4j -->
  <dependency>
   <groupId>dev.langchain4j</groupId>
   <artifactId>langchain4j</artifactId>
  </dependency>
  <dependency>
   <groupId>dev.langchain4j</groupId>
   <artifactId>langchain4j-open-ai</artifactId>
  </dependency>
  <!-- Langgraph4j -->
  <dependency>
   <groupId>org.bsc.langgraph4j</groupId>
   <artifactId>langgraph4j-core</artifactId>
  </dependency>
 </dependencies>

</project>
