<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
 <modelVersion>4.0.0</modelVersion>
 <parent>
  <groupId>labs</groupId>
  <artifactId>labs</artifactId>
  <version>${revision}</version>
 </parent>
 <groupId>labs.apps</groupId>
 <artifactId>apps</artifactId>
 <packaging>pom</packaging>
 
 <modules>
  <!--module>ai</module-->
  <module>backend</module>
  <!--module>frontend</module-->
  <!--module>fullstack</module-->
 </modules>

</project>
