<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
 <modelVersion>4.0.0</modelVersion>
 <parent>
  <groupId>labs.apps.backend</groupId>
  <artifactId>backend</artifactId>
  <version>${revision}</version>
 </parent>
 <groupId>labs.apps.backend.java</groupId>
 <artifactId>java</artifactId>
 <packaging>pom</packaging>
 
 <properties>
  <java.version>25</java.version>
  <maven.compiler.source>25</maven.compiler.source>
  <maven.compiler.target>25</maven.compiler.target>
  <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  <maven-compiler-plugin.version>3.15.0</maven-compiler-plugin.version>
 </properties>
 
 <modules>
  <module>spring</module>
  <!--module>quarkus</module-->
  <!--module>helidon</module-->
  <module>langchain4j</module>
  <module>langgraph4j</module>
 </modules>
 
 <build>
  <plugins>
   <plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>${maven-compiler-plugin.version}</version>
   </plugin>
  </plugins>
 </build>
 
 <!-- LangGraph4j-->
 <repositories>
  <repository>
   <id>sonatype-oss-snapshots</id>
   <url>https://central.sonatype.com/repository/maven-snapshots</url>
   <snapshots>
    <enabled>true</enabled>
   </snapshots>
  </repository>
 </repositories>

</project>
